### ISSUE TITLE
Type checking doesn't work: fileExists is not a function

### ISSUE THREAD

**Issue by frigus02** [frigus02/vscode-sql-tagged-template-literals#27]
The TS Server logs show:

```
Err 153   [20:19:01.149] Exception on executing command delayed processing of request 15:

    host.fileExists is not a function

    TypeError: host.fileExists is not a function
        at Object.fileExists (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:141803:38)
        at Object.host.fileExists (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:117916:41)
        at getPackageJsonInfo (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:42484:31)
        at loadModuleFromSpecificNodeModulesDirectory (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:43127:21)
        at loadModuleFromImmediateNodeModulesDirectory (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:43104:27)
        at /home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:43092:31
        at forEachAncestorDirectory (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:9180:20)
        at lookup (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:43086:12)
        at loadModuleFromNearestNodeModulesDirectoryWorker (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:43078:20)
        at loadModuleFromNearestNodeModulesDirectory (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:43048:10)
        at tryResolve (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:42114:21)
        at nodeModuleNameResolverWorker (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:42056:36)
        at nodeModuleNameResolver (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:42010:10)
        at resolveModuleName (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:41760:18)
        at resolveLibrary (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:41696:10)
        at actualResolveLibrary (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:118652:68)
        at pathForLibFileWorker (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120578:24)
        at pathForLibFile (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120546:20)
        at /home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120594:11
        at forEach (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:2325:22)
        at processLibReferenceDirectives (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120590:5)
        at findSourceFileWorker (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120351:9)
        at findSourceFile (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120218:20)
        at /home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120167:22
        at getSourceFileFromReferenceWorker (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120136:26)
        at processSourceFile (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:120165:5)
        at processRootFile (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:119962:5)
        at createProgram (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:118757:9)
        at synchronizeHostData (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:141865:15)
        at Object.getSemanticDiagnostics (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:142012:5)
        at /home/jan/vscode-sql-tagged-template-literals/extension/node_modules/typescript-sql-tagged-template-plugin/build/type-checker.js:13:87
        at VirtualServiceHost.withFile (/home/jan/vscode-sql-tagged-template-literals/extension/node_modules/typescript-sql-tagged-template-plugin/build/virtual-service-host.js:12:24)
        at TypeChecker.check (/home/jan/vscode-sql-tagged-template-literals/extension/node_modules/typescript-sql-tagged-template-plugin/build/type-checker.js:13:40)
        at /home/jan/vscode-sql-tagged-template-literals/extension/node_modules/typescript-sql-tagged-template-plugin/build/language-service.js:169:37
        at Array.map (<anonymous>)
        at SqlTemplateLanguageService.getSemanticDiagnostics (/home/jan/vscode-sql-tagged-template-literals/extension/node_modules/typescript-sql-tagged-template-plugin/build/language-service.js:160:14)
        at TemplateLanguageServiceProxy.adaptDiagnosticsCall (/home/jan/vscode-sql-tagged-template-literals/extension/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:291:38)
        at Proxy.<anonymous> (/home/jan/vscode-sql-tagged-template-literals/extension/node_modules/typescript-template-language-service-decorator/lib/template-language-service-decorator.js:54:25)
        at IpcIOSession.semanticCheck (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:180632:125)
        at /home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:180693:14
        at MultistepOperation.executeAction (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:179355:9)
        at /home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:179335:69
        at IpcIOSession.executeWithRequestId (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:182345:14)
        at Object.executeWithRequestId (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:180378:57)
        at Immediate._onImmediate (/home/jan/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/node_modules/typescript/lib/tsserver.js:179335:26)
        at processImmediate (node:internal/timers:468:21)
```

I updated TypeScript because I remember it made some fileExists function mandatory in one of the last releases. But I don't see any type errors. I wonder where this goes wrong.

_Originally posted by @frigus02 in https://github.com/frigus02/vscode-sql-tagged-template-literals/issues/26#issuecomment-1604674699_

**Comment by frigus02** [comment]
Loading the plugin via a locally installed node_module rather than the extension works, at least using the "Workspace Version" for the VS Code TypeScript version.

**Comment by frigus02** [comment]
VS Code 1.79.2

**Comment by frigus02** [comment]
Oh damn. I updated the TS dependency in typescript-sql-tagged-template-plugin a while ago but never released a new version. 🤦

**Comment by GerkinDev** [comment]
Hey there, I had this also, and managed to fix it somehow by forcing the vscode plugin to use a locally installed & built version of the sql extension. I also suspected some API changes in TS, but even with 5.x, the locally built lib worked just fine.

**Comment by frigus02** [comment]
I published typescript-sql-tagged-template-plugin v0.3.0 now.

With that, this extension also works again. I'm going to publish an update in a minute...

**Comment by GerkinDev** [comment]
Great job! I can't wait showcasing this to my coworkers

**Comment by frigus02** [comment]
Extension is uploaded. Currently verifying. Should be available in the next few minutes to hours.

**Comment by frigus02** [comment]
It's available now. Just verified that it works for me.
